# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
- name: success
  displayName: Success or Fail
  type: boolean
  default: false
  
trigger:
- Tracy_test_azure-pipelines

pool:
  vmImage: ubuntu-latest

jobs:
- job: Work
  steps: 
  - script: echo Hello World!
    displayName: "Run a on-line script"
- job:    
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
    
- job: ErrorHandler
  dependsOn: Work
  condition: success()
  steps:
  - bash: |
      az boards work-item create \
        --title "Build $(build.buildNumber) failed" \
        --type bug \
        --org $(System.TeamFoundationCollectionUri) \
        --project $(System.TeamProject)

    env:
     AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
  displayName: 'Create work item on failure'
